# Generated by Django 6.0.5 on 2026-05-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_page_created_at_remove_page_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
