# Generated by Django 5.2.14 on 2026-05-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStylesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Stylesheet',
                'verbose_name_plural': 'Site Stylesheet',
            },
        ),
        migrations.AlterField(
            model_name='footer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
