# Generated by Django 5.2.14 on 2026-05-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_seed_sitestylesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootstrapOverrides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Bootstrap Overrides',
                'verbose_name_plural': 'Bootstrap Overrides',
            },
        ),
    ]
