# Generated by Django 5.2.14 on 2026-05-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_seed_bootstrapoverrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='style',
            field=models.CharField(choices=[('default', 'Default — bordered card with light background'), ('no_background', 'No Background — clean, text only'), ('custom_font', 'Custom Font — large serif display style')], default='default', max_length=20),
        ),
    ]
