# Generated by Django 5.2.14 on 2026-05-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_update_stylesheet_block_styles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Contact Us', max_length=200)),
                ('intro_text', models.TextField(blank=True, help_text='Introductory paragraph shown at the top of the page')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True, help_text='Physical address — each line will be shown separately')),
                ('opening_hours', models.TextField(blank=True, help_text='E.g. Mon–Fri 9am–5pm')),
                ('extra_info', models.TextField(blank=True, help_text='Any additional information to display at the bottom')),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Page',
            },
        ),
        migrations.AlterField(
            model_name='bootstrapoverrides',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitestylesheet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
