# Generated by Django 5.2.14 on 2026-05-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_fix_scrollbar_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Shoppalist', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
