# Generated by Django 5.2.14 on 2026-05-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_add_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blocks/'),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
