# Generated by Django 5.2.14 on 2026-05-13 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_textblock_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Assign to a page, or leave blank to show on the home page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='pages.page'),
        ),
    ]
