# Generated by Django 5.2.14 on 2026-05-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_page_updated_at_textblock_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_format',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML')], default='markdown', max_length=10),
        ),
        migrations.AddField(
            model_name='textblock',
            name='content_format',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML')], default='markdown', max_length=10),
        ),
    ]
