# Generated by Django 6.0.5 on 2026-05-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_add_content_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textblock',
            name='image',
        ),
        migrations.RemoveField(
            model_name='textblock',
            name='image_align',
        ),
        migrations.RemoveField(
            model_name='textblock',
            name='image_width',
        ),
    ]
