# Generated by Django 5.2.14 on 2026-05-13 00:50

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0011_update_stylesheet_block_styles'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContent',
            fields=[
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.footer',),
        ),
        migrations.CreateModel(
            name='TextBlockContent',
            fields=[
            ],
            options={
                'verbose_name': 'Text Block',
                'verbose_name_plural': 'Text Blocks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.textblock',),
        ),
    ]
